spring:
    #???????
    datasource:
    ##???????
    #type: com.alibaba.druid.pool.DruidDataSource
    #??????????
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://graduate-23f-db-database.dev.juyuansoft.com:3306/sakila?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
        username: readonly
        password: RD12345678
